### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by BigDeepBlue** [anderskate/Fast_API_sprint_1#15]
Мне в трекер пришла пустая работа, поэтому я вам вернул работу с комментарием, что у вас ничего нет. Только потом я обнаружил у вас ссылочку в README и пришел сюда, прошу прощения. 

У вас получилась хорошая работа, но с небольшими замечаниями. Важно поправить пагинацию.

- Вот в [этом](https://github.com/anderskate/Fast_API_sprint_1/blob/master/src/api/v1/person.py#L29) месте вам лучше убрать наложение резолва урлов, т.к. выше, вмесето `search` может стоять чей-то `person_id`. Лучше сделать отдельный урл для сервиса поиска, типа `/api/v1/search/persons/`, либо через GET параметры `/api/v1/persons/?search=whaaugeh`. Это сделает структуру адресов ресурсов более стройной и REST подобной.
- [Пагинацию](https://github.com/anderskate/Fast_API_sprint_1/blob/master/src/api/v1/person.py#L36) нужно реализовать на уровне эластика. Поисковый запрос вполне может вернуть 10К позиций. 
Т.е. получать в запросе от клиента limit и page и передавать в эластик как то так:
```
es_body = {
    'size': limit,
    'from': (page - 1) * limit,
}
```
- В Python 3.9 можно не использовать [эти](https://github.com/anderskate/Fast_API_sprint_1/blob/master/src/api/v1/person.py#L2) тайпинги, а использовать нативные типы https://www.python.org/dev/peps/pep-0585/
- Все сказанное выше относится и к другим эндпоинтам, не только к `persons`
- Вот эти [Config](https://github.com/anderskate/Fast_API_sprint_1/blob/master/src/models/movie.py#L22) в pydantic наследуются, так что можно написать базовую pydantic модель, наследоваться от нее и не копипастить.

**Comment by BigDeepBlue** [comment]
@anderskate тут ревью

**Comment by anderskate** [comment]
@BigDeepBlue Внесли правки по код ревью

**Comment by BigDeepBlue** [comment]
Все очень классно, большое спасибо за доработку! Зачет!
